src/Entity/TasksModel.php
<?php

namespace App\Entity;

use App\Repository\TasksModelRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Table(name: 'tasks')]
#[ORM\Entity(repositoryClass: TasksModelRepository::class)]
class TasksModel
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $user_id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column]
    private ?\DateTime $due_date = null;

    #[ORM\Column(length: 255)]
    private ?int $status = null;

    #[ORM\Column]
    private ?int $priority = null;

    #[ORM\ManyToOne(targetEntity: Events::class)]
    #[ORM\JoinColumn(name: "event_id", referencedColumnName: "id", nullable: false)]
    private ?Events $event = null;

    #[ORM\Column]
    private $event_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): static
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDueDate(): ?\DateTime
    {
        return $this->due_date;
    }

    public function setDueDate(\DateTime $due_date): static
    {
        $this->due_date = $due_date;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(int $priority): static
    {
        $this->priority = $priority;

        return $this;
    }

    public function getEventId(): ?int
    {
        return $this->event_id;
    }

    public function setEventId($event_id): static
    {
        $this->event_id = $event_id;

        return $this;
    }

    public function getEvent(): ?Events
    {
        return $this->event;
    }

    public function setEvent(?Events $event): self
    {
        $this->event = $event;
        return $this;
    }

}

src/Controller/ToDoListController.php
<?php

namespace App\Controller;

use App\Entity\TasksModel;
use App\Form\TaskType;
use App\Repository\TasksModelRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

final class ToDoListController extends AbstractController
{
    public function __construct(private EntityManagerInterface $entityManager,
                                private TasksModelRepository   $tasksRepository)
    {

    }

    #[IsGranted('ROLE_USER')]
    #[Route('/to-do-list', name: 'web_tasks')]
    public function index(
        PaginatorInterface $paginator,
        Request            $request
    ): Response
    {
        $query = $this->tasksRepository->createQueryBuilder('t')->getQuery();

        $pagination = $paginator->paginate(
            $query, // Query to paginate
            $request->query->getInt('page', 1), // Current page number
            10 // Items per page
        );

        return $this->render('to_do_list/index.html.twig', [
            'tasks' => $pagination,
        ]);
    }

    #[IsGranted('ROLE_USER')]
    #[Route('/to-do-list/create', name: 'app_tasks_new')]
    public function create(
        Request $request
    ): Response
    {
        $task = new TasksModel();
        $form = $this->createForm(TaskType::class, $task);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $event_id = $request->request->all()['task']['event'] ?? null;
            $task->setEventId($event_id);;
            $this->entityManager->persist($task);
            $this->entityManager->flush();

            return $this->redirectToRoute('web_tasks');
        }

        return $this->render('to_do_list/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[IsGranted('ROLE_USER')]
    #[Route('/to-do-list/edit/{id}', name: 'app_tasks_edit')]
    public function edit(
        Request $request,
                $id
    ): Response
    {
        $task = $this->tasksRepository->find($id);

        if (!$task) {
            throw $this->createNotFoundException('Task not found');
        }

        $form = $this->createForm(TaskType::class, $task);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($task);
            $this->entityManager->flush();

            return $this->redirectToRoute('web_tasks');
        }

        return $this->render('to_do_list/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[IsGranted('ROLE_USER')]
    #[Route('/to-do-list/toggle/{id}', name: 'app_tasks_toggle')]
    public function markAsComplete(
        Request $request,
                $id
    ): Response
    {
        $task = $this->tasksRepository->find($id);

        if (!$task) {
            throw $this->createNotFoundException('Task not found');
        }

        if ($task->getStatus() == 0 || $task->getStatus() == 1) {
            $task->setStatus(2);
        } else {
            $task->setStatus(1);
        }

        $this->entityManager->persist($task);
        $this->entityManager->flush();

        return $this->redirectToRoute('web_tasks');
    }

    #[IsGranted('ROLE_USER')]
    #[Route('/to-do-list/delete/{id}', name: 'app_tasks_delete')]
    public function delete(
        Request $request,
                $id
    ): Response
    {
        $task = $this->tasksRepository->find($id);

        if (!$task) {
            throw $this->createNotFoundException('Task not found');
        }

        $this->entityManager->remove($task);
        $this->entityManager->flush();
        return $this->redirectToRoute('web_tasks');
    }

}

templates/to_do_list/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create New Task{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/to-do-list.css') }}">
{% endblock %}

{% block body %}
    <div class="container content my-4">
        <h1>Create a New Task</h1>

        <div class="mb-3">
            {{ form_start(form) }}

            <div class="mb-3">
                {{ form_label(form.title) }}
                {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.title) }}
            </div>

            <div class="mb-3">
                {{ form_label(form.description) }}
                {{ form_widget(form.description, {'attr': {'class': 'form-control', 'rows': 4}}) }}
                {{ form_errors(form.description) }}
            </div>

            <div class="mb-3">
                {{ form_label(form.due_date) }}
                {{ form_widget(form.due_date, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.due_date) }}
            </div>

            <div class="mb-3">
                {{ form_label(form.event) }}
                {{ form_widget(form.event, {'attr': {'class': 'form-select'}}) }}
                {{ form_errors(form.event) }}
            </div>

            <div class="mb-3">
                {{ form_label(form.priority) }}
                {{ form_widget(form.priority, {'attr': {'class': 'form-select'}}) }}
                {{ form_errors(form.priority) }}
            </div>

            <div class="mb-3">
                {{ form_label(form.status) }}
                {{ form_widget(form.status, {'attr': {'class': 'form-select'}}) }}
                {{ form_errors(form.status) }}
            </div>

            <div class="mb-3 d-none">
                {{ form_label(form.user_id) }}
                {{ form_widget(form.user_id, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.user_id) }}
            </div>

            <button type="submit" class="btn btn-primary" id="task_submit">Create Task</button>
            {{ form_end(form) }}
        </div>

    </div>
{% endblock %}

templates/to_do_list/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Task{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/to-do-list.css') }}">
{% endblock %}

{% block body %}
    <div class="container content my-4">
        <h1>Edit Task</h1>

        <div class="mb-3">
            {{ form_start(form) }}

            <div class="mb-3">
                {{ form_label(form.title) }}
                {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.title) }}
            </div>

            <div class="mb-3">
                {{ form_label(form.description) }}
                {{ form_widget(form.description, {'attr': {'class': 'form-control', 'rows': 4}}) }}
                {{ form_errors(form.description) }}
            </div>

            <div class="mb-3">
                {{ form_label(form.due_date) }}
                {{ form_widget(form.due_date, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.due_date) }}
            </div>

            <div class="mb-3">
                {{ form_label(form.event) }}
                {{ form_widget(form.event, {'attr': {'class': 'form-select'}}) }}
                {{ form_errors(form.event) }}
            </div>

            <div class="mb-3">
                {{ form_label(form.priority) }}
                {{ form_widget(form.priority, {'attr': {'class': 'form-select'}}) }}
                {{ form_errors(form.priority) }}
            </div>

            <div class="mb-3">
                {{ form_label(form.status) }}
                {{ form_widget(form.status, {'attr': {'class': 'form-select'}}) }}
                {{ form_errors(form.status) }}
            </div>

            <div class="mb-3 d-none">
                {{ form_label(form.user_id) }}
                {{ form_widget(form.user_id, {'attr': {'class': 'form-control'}}) }}
                {{ form_errors(form.user_id) }}
            </div>

            <button type="submit" class="btn btn-primary" id="task_submit">Update The Task</button>
            {{ form_end(form) }}
        </div>

    </div>
{% endblock %}

templates/to_do_list/index.html.twig
{# templates/task/index.html.twig #}
{% extends 'base.html.twig' %}

{% block title %}My Tasks{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/to-do-list.css') }}">
{% endblock %}

{% block body %}
    <div class="container content my-4">
        <h1>My To-Do List</h1>

        <div class="row">
            <div class="col-md-6">

            </div>
            <div class="col-md-6">
                <div class="mb-3 d-flex justify-content-end">
                    <a href="{{ path('app_tasks_new') }}" class="btn btn-primary">Add New Task</a>
                </div>
            </div>
        </div>


        {% if tasks is empty %}
            <p>No tasks found. Start by adding a new task!</p>
        {% else %}
            <div class="list-group">
                {% for task in tasks %}
                    <div class="list-group-item {% if task.status == 2 %}list-group-item-success{% endif %}">
                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                                <h5 class="mb-1">{{ task.title }}</h5>
                                {% if task.description %}
                                    <p class="mb-1">{{ task.description }}</p>
                                {% endif %}

                                {% if task.dueDate %}
                                    <small>Due: {{ task.dueDate|date('Y-m-d H:i') }}</small>
                                {% endif %}

                                <div class="mt-2">
                                <span class="badge bg-{% if task.priority == 0 %}secondary{% elseif task.priority == 1 %}primary{% else %}danger{% endif %}">
                                    {% if task.priority == 0 %}
                                        Low
                                    {% elseif task.priority == 1 %}
                                        Medium
                                    {% else %}
                                        High
                                    {% endif %}
                                </span>
                                </div>
                            </div>

                            <div>
                                <a href="{{ path('app_tasks_edit', {'id': task.id}) }}" class="btn btn-sm btn-outline-primary">Edit</a>
                                <a href="{{ path('app_tasks_toggle', {'id': task.id}) }}" class="btn btn-sm btn-outline-{% if task.status %}secondary{% else %}success{% endif %}">
                                    {% if task.status ==2  %}Mark as Incomplete{% else %}Mark as Complete{% endif %}
                                </a>
                                <a href="{{ path('app_tasks_delete', {'id': task.id}) }}" class="btn btn-sm btn-outline-danger">Delete</a>
                            </div>
                        </div>

                        {% if task.subtasks is defined and task.subtasks is not empty %}
                            <div class="mt-3">
                                <strong>Subtasks:</strong>
                                <ul class="list-group mt-2">
                                    {% for subtask in task.subtasks %}
                                        <li class="list-group-item d-flex justify-content-between align-items-center">
                                            {{ subtask.title }}
                                            <div>
                                            <span class="badge bg-{% if subtask.isCompleted %}success{% else %}secondary{% endif %} rounded-pill">
                                                {% if subtask.isCompleted %}Completed{% else %}Pending{% endif %}
                                            </span>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
            <div class="mt-4 mb-4">
                {{ knp_pagination_render(tasks) }}
            </div>
        {% endif %}
    </div>
{% endblock %}